export const exclusions = {
  directoryExclusions: [
    "node_modules",
    "dist",
    "build",
    "coverage",
    ".next",
    ".cache",
    ".temp",
    "tmp",
    "out",
    "lib",
    "public",
    "storybook-static",
    ".git",
    ".svn",
    "android",
    "ios",
    ".expo",
    ".expo-shared",
    ".gradle",
    "vendor",
    "Pods",
    "__tests__",
    "__snapshots__",
    "__mocks__",
    "__fixtures__",
    "e2e",
    ".idea",
    ".vscode",
    ".vs",
    ".history",
    ".husky",
  ],
  fileExclusions: [
    ".DS_Store",
    "Thumbs.db",
    "package-lock.json",
    "yarn.lock",
    "npm-debug.log",
    "yarn-debug.log",
    "yarn-error.log",
    "pnpm-lock.yaml",

    ".env",
    ".env.local",
    ".env.development",
    ".env.test",
    ".env.production",
    ".gitignore",
    ".eslintignore",
    ".prettierignore",
    ".eslintrc",
    ".eslintrc.js",
    ".eslintrc.json",
    ".prettierrc",
    ".prettierrc.js",
    ".prettierrc.json",
    "tsconfig.json",
    "tsconfig.*.json",
    "babel.config.js",
    "metro.config.js",
    "jest.config.js",
    "jest.setup.js",

    "app.json",
    "app.config.js",
    "eas.json",
    "Podfile",
    "Podfile.lock",
    "Gemfile",
    "Gemfile.lock",
    "gradlew",
    "gradlew.bat",
    "local.properties",
    "*.keystore",
    "*.jks",

    "*.log",
    "report.html",
    "coverage.xml",
    "junit.xml",

    "*.map",
    "*.d.ts",
    "*.tsbuildinfo",
    "*.min.js",
    "*.min.css",

    ".npmrc",
    ".yarnrc",
    "*.lock",
    "*.tmp",
    "*.temp",
  ],
  prefixExclusions: [".", "_", "#"],
};
